apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api-inw-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-inw-prod
  template:
    metadata:
      labels:
        app: api-inw-prod
    spec:
      containers:
      - name: api-inw-prod
        image: gcr.io/appDomain-123456/api-inw-prod:latest
        ports:
        - containerPort: 8000
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: production
                key: MONGODB_URI
          - name: GOOGLE_MAP_API_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: GOOGLE_MAP_API_KEY
          - name: GOOGLE_PROJECT_ID
            valueFrom:
              secretKeyRef:
                name: default
                key: GOOGLE_PROJECT_ID
          - name: SENDGRID_API_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: SENDGRID_API_KEY
          - name: CRON_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: CRON_SECRET_KEY
          - name: ACTIVITY_LOG_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: ACTIVITY_LOG_KEY
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: default
                key: JWT_SECRET
          - name: JWT_ALGORITHM
            valueFrom:
              secretKeyRef:
                name: default
                key: JWT_ALGORITHM
          - name: JWT_ISSUER
            valueFrom:
              secretKeyRef:
                name: default
                key: JWT_ISSUER
          - name: JWT_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: default
                key: JWT_AUDIENCE
          - name: RS_USERNAME
            valueFrom:
              secretKeyRef:
                name: default
                key: RS_USERNAME
          - name: RS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: default
                key: RS_PASSWORD
          - name: SSL_KEY_PASS
            valueFrom:
              secretKeyRef:
                name: default
                key: SSL_KEY_PASS
          - name: SENTRY_KEY
            valueFrom:
              secretKeyRef:
                name: default
                key: SENTRY_KEY
