apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-inw
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: api-dev.appDomain.com
    http:
      paths:
      - backend:
          serviceName: api-inw-dev
          servicePort: 8000
  - host: api-staging.appDomain.com
    http:
      paths:
      - backend:
          serviceName: api-inw-staging
          servicePort: 8000
  - host: api.appDomain.com
    http:
      paths:
      - backend:
          serviceName: api-inw-prod
          servicePort: 8000
  - host: api-myid.vobi.io
    http:
      paths:
      - backend:
          serviceName: dev-api-myid
          servicePort: 8000
